### ISSUE TITLE
Changed column alias results in error

### ISSUE THREAD

**Issue by karl-project-review** [vibiii/sql-scratch-capstone-turn-in#1]
https://github.com/vibiii/sql-scratch-capstone-turn-in/blob/250b89b043a02dc0fd3f77aa6e91fe77071e6a80/Capstone%20VBroly/code.sql#L69-L73
Note that in the SELECT statement, the count is aliased as total_answers, but in the ORDER BY statement, it is referred to as number_answers instead, resulting in an error. Be careful about using the proper names and avoiding typos like this.

**Comment by vibiii** [comment]
The query worked so I am pretty sure I have changed the alias when pasting the query on th sql doc but didn't change it everywhere.
Sorry for that
