### ISSUE TITLE
Missing semi colon and changed alias result in error

### ISSUE THREAD

**Issue by karl-project-review** [vibiii/sql-scratch-capstone-turn-in#2]
https://github.com/vibiii/sql-scratch-capstone-turn-in/blob/250b89b043a02dc0fd3f77aa6e91fe77071e6a80/Capstone%20VBroly/code.sql#L114-L117
We need a semi colon at the end of this query, or else we get an error. Also, note that in the SELECT statement the alias purchase_black is used, but in the GROUP BY statement the alias purchase_color is used instead, which will cause an error (similar to issue #1).

**Comment by vibiii** [comment]
Again I think it happened when pasting the query....
