### ISSUE TITLE
Avoid unnecessary tables and columns to increase query efficiency

### ISSUE THREAD

**Issue by karl-project-review** [vibiii/sql-scratch-capstone-turn-in#3]
https://github.com/vibiii/sql-scratch-capstone-turn-in/blob/250b89b043a02dc0fd3f77aa6e91fe77071e6a80/Capstone%20VBroly/code.sql#L53-L67
Since we are working with relatively small tables, efficiency isn't as much of an issue in this project, but if we were working with larger tables, we would want to make sure to avoid unnecessary JOINs and SELECTing unnecessary columns. For example, in the above query for finding the results of the AB test, we don't need the quiz table at all, as your query screens out all of the users who appear in the quiz table but not the home_try_on table. Also, instead of making the is_purchase column contain 'True' and 'False' strings in the funnel clause and then converting this into 1s and 0s when computing the conversion_rate in the main query, we can just make them 1s and 0s initially by assessing the "truthiness" of the statement `p.user_id IS NOT NULL` (as this will return 1 for every row where this is true and 0 for every row where it is not). Below is a revised version of your query which should run faster and return the same results:
```sql
WITH funnel AS (
  SELECT h.user_id,
    h.number_of_pairs,
    p.user_id IS NOT NULL AS 'is_purchase'
  FROM  home_try_on AS h
  LEFT JOIN purchase AS p
    ON h.user_id = p.user_id)
SELECT number_of_pairs, 
  COUNT (*) AS total_users, 
  1.0*SUM (is_purchase) / COUNT(*) AS conversion_rate
FROM funnel
GROUP BY number_of_pairs;
```

**Comment by vibiii** [comment]
I re-used the funnel query for this one but indeed you are right I should have modified it to remove the JOIN on the quiz table.
Thanks for the comment on the is_purchase column, it is indeed much simpler the way you have done it.
