### ISSUE TITLE
Capitalize COUNT, SUM, ON, and AS

### ISSUE THREAD

**Issue by karl-project-review** [vibiii/sql-scratch-capstone-turn-in#4]
https://github.com/vibiii/sql-scratch-capstone-turn-in/blob/250b89b043a02dc0fd3f77aa6e91fe77071e6a80/Capstone%20VBroly/code.sql#L108-L117
For the most part, you've done a good job of capitalizing the reserved keywords, but keep in mind that COUNT and SUM are reserved keywords, too. Also, make sure to consistently capitalize AS and ON as well (you do this in some places, but not, for instance, in some of the lines in the code sample above). This will make it easier to quickly scan through your queries.

**Comment by vibiii** [comment]
Ok noted thanks
