### ISSUE TITLE
Put each column being SELECTed on its own line

### ISSUE THREAD

**Issue by karl-project-review** [vibiii/sql-scratch-capstone-turn-in#5]
https://github.com/vibiii/sql-scratch-capstone-turn-in/blob/250b89b043a02dc0fd3f77aa6e91fe77071e6a80/Capstone%20VBroly/code.sql#L121
You split up the columns being SELECTed onto their own lines in some places, but not in others, and it would help improve readability if you did so consistently, as this would help prevent overly long lines. For example, the above SELECT statement could be broken up like so:
```sql
SELECT product_id, 
  style, 
  model_name, 
  color, 
  COUNT(*) AS total_purchases
```

**Comment by vibiii** [comment]
OK noted thanks !
