### ISSUE TITLE
Use indentation for differentiation between different parts of queries

### ISSUE THREAD

**Issue by karl-project-review** [vibiii/sql-scratch-capstone-turn-in#6]
https://github.com/vibiii/sql-scratch-capstone-turn-in/blob/250b89b043a02dc0fd3f77aa6e91fe77071e6a80/Capstone%20VBroly/code.sql#L39-L51
Indentation can provide useful visual cues for when a WITH clause ends and which lines are just continuations of the same statement (for example, the different columns in a single SELECT statement or the ON lines in a JOIN). Below is a reformatted version of your query above that uses indentation to provide these visual cues (I also made some changes similar to in issue #3 to have the is_purchase and is_home_try columns be 1s and 0s initially):
```sql
 -- Question 6 - Query 1 : overall conversion rates 
WITH funnel AS (
  SELECT q.user_id, 
    h.user_id IS NOT NULL AS 'is_home_try', 
    h.number_of_pairs, 
    p.user_id IS NOT NULL AS 'is_purchase' 
  FROM quiz AS q 
  LEFT JOIN home_try_on AS h
    ON q.user_id = h.user_id 
  LEFT JOIN purchase AS p 
    ON h.user_id = p.user_id) 
SELECT COUNT (DISTINCT user_id) AS 'quiz', 
  SUM (is_home_try) AS 'home_try', 
  SUM (is_purchase ) AS 'purchase' 
FROM funnel; 
```

**Comment by vibiii** [comment]
Ok noted thanks for that.
Identation is not deeply addressed in the course but I will try to find information on that in order to improve the readability of my code.
