### ISSUE TITLE
Warby Parker Project Summary & Rubric Score

### ISSUE THREAD

**Issue by karl-project-review** [vibiii/sql-scratch-capstone-turn-in#7]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all answers?
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ You included appropriate queries and the results of those queries for each of the questions. What's more, you provided reasonable analysis of those results and used this to formulate clear, actionable recommendations. I particularly liked your analysis of the purchasing habits of people who selected black as their preferred color in the quiz, as it brings up some interesting questions. Good work!
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 3/4 (Meets Expectations)
* _Comment(s):_ Most of your queries retrieve the rows they are supposed to. Well done! However, their were two instances of columns being referred to by the wrong alias and one instance of a missing semi-colon, resulting in errors. These are described in more detail in issues #1 and #2. It looks like you have the data that these queries were supposed to retrieve in your report, though, so I'm not sure if these errors were introduced into your code when you were reformatting it for submission? Also, as mentioned in issue #3, you could improve the efficiency of some of your queries by not including unnecessary tables and by converting columns to the format you are looking for more directly.
### Criteria 3: Query Formatting
* _Score Level:_ 3/4 (Meets Expectations)
* _Comment(s):_ Your code adheres to many of the formatting guidelines, but there were some reserved keywords that were not capitalized (see issue #4) and some SELECT clauses that should be split up into multiple lines (#5). Also, be sure to use indentation to improve readability (#6).
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 3/4 (Meets Expectations)
* _Comment(s):_ You demonstrated a clear understanding of the purchase funnel, but your analysis in slides 1.2 and 1.3 indicates some misconceptions about the quiz funnel. Since users have to answer each question to be able to answer the next (even if they answer it with 'Not sure. Let's skip it.'), the response rate for question 4 is actually pretty high, as while only 72% of users who started the quiz answered it, 95% (=361/380) of people who had answered question 3 (and thus were eligible to answer question 4) did in fact answer question 4. In general, since this is a funnel where people can drop out altogether after each step, the degree to which a question affects the drop out rate is better measured by the percentage of people who answered the preceding question who also answered this one, rather than the percent of people who started the quiz who also answered this question. 

### Overall Score: 13/16 (Meets Expectations)
Well done on this overall! Most of your queries do what they should, and the additional analysis you chose to perform posed the right sort of questions to gain insight from the available data. Do watch out for typos that can causes errors in your queries, though, and keep in mind ways to make your queries more efficient (as when working with larger tables, this can make a significant difference in runtime). Good luck as you move forward with your database querying!

**Comment by vibiii** [comment]
Thank you very much for your review and the tips you provided me with.
I will do my best to improve my code, starting by avoiding those stupid typos !
